/* Generated By:JJTree&JavaCC: Do not edit this line. ADTParserConstants.java */
package adtool.adtree;


/**
 * Token literal values and constants.
 */
public interface ADTParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OO = 5;
  /** RegularExpression Id. */
  int AO = 6;
  /** RegularExpression Id. */
  int OP = 7;
  /** RegularExpression Id. */
  int AP = 8;
  /** RegularExpression Id. */
  int CO = 9;
  /** RegularExpression Id. */
  int CP = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int LPAREN = 12;
  /** RegularExpression Id. */
  int RPAREN = 13;
  /** RegularExpression Id. */
  int IDENTIFIER = 14;
  /** RegularExpression Id. */
  int FIRST_CHAR = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int SPACE = 18;
  /** RegularExpression Id. */
  int EOL = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<OO>",
    "<AO>",
    "<OP>",
    "<AP>",
    "<CO>",
    "<CP>",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<IDENTIFIER>",
    "<FIRST_CHAR>",
    "<LETTER>",
    "<DIGIT>",
    "<SPACE>",
    "<EOL>",
  };

}
