/* Generated By:JavaCC: Do not edit this line. ADTParserTreeConstants.java Version 5.0 */
package adtool.adtree;

public interface ADTParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTADTOPP = 1;
  public int JJTADTPRO = 2;


  public String[] jjtNodeName = {
    "void",
    "ADTOpp",
    "ADTPro",
  };
}
/* JavaCC - OriginalChecksum=47eeb958d5a08cbf3b50bfe572b22449 (do not edit this line) */
